apiVersion: v1
kind: Service
metadata:
  labels:
    app: spin-doctor
  name: spin-doctor
  namespace: spinnaker
spec:
  ports:
  - name: http
    port: 7002
    protocol: TCP
    targetPort: http
  selector:
    app: spin-doctor
