apiVersion: v1
kind: Service
metadata:
  labels:
    app: spin-router
  name: spin-router
  namespace: spinnaker
spec:
  ports:
  - nodePort: 31493
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: spin-router
