apiVersion: v1
kind: Service
metadata:
  labels:
    app: spin
    cluster: spin-clouddriver
  name: spin-clouddriver
  namespace: spinnaker
spec:
  ports:
  - name: http
    port: 7002
    protocol: TCP
    targetPort: 7002
  selector:
    app: spin
    cluster: spin-clouddriver
