// Code generated by counterfeiter. DO NOT EDIT.
package fiatfakes

import (
	"sync"

	"github.com/homedepot/go-clouddriver/pkg/fiat"
)

type FakeClient struct {
	AuthorizeStub        func(account string) (fiat.Response, error)
	authorizeMutex       sync.RWMutex
	authorizeArgsForCall []struct {
		account string
	}
	authorizeReturns struct {
		result1 fiat.Response
		result2 error
	}
	authorizeReturnsOnCall map[int]struct {
		result1 fiat.Response
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) Authorize(account string) (fiat.Response, error) {
	fake.authorizeMutex.Lock()
	ret, specificReturn := fake.authorizeReturnsOnCall[len(fake.authorizeArgsForCall)]
	fake.authorizeArgsForCall = append(fake.authorizeArgsForCall, struct {
		account string
	}{account})
	fake.recordInvocation("Authorize", []interface{}{account})
	fake.authorizeMutex.Unlock()
	if fake.AuthorizeStub != nil {
		return fake.AuthorizeStub(account)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.authorizeReturns.result1, fake.authorizeReturns.result2
}

func (fake *FakeClient) AuthorizeCallCount() int {
	fake.authorizeMutex.RLock()
	defer fake.authorizeMutex.RUnlock()
	return len(fake.authorizeArgsForCall)
}

func (fake *FakeClient) AuthorizeArgsForCall(i int) string {
	fake.authorizeMutex.RLock()
	defer fake.authorizeMutex.RUnlock()
	return fake.authorizeArgsForCall[i].account
}

func (fake *FakeClient) AuthorizeReturns(result1 fiat.Response, result2 error) {
	fake.AuthorizeStub = nil
	fake.authorizeReturns = struct {
		result1 fiat.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) AuthorizeReturnsOnCall(i int, result1 fiat.Response, result2 error) {
	fake.AuthorizeStub = nil
	if fake.authorizeReturnsOnCall == nil {
		fake.authorizeReturnsOnCall = make(map[int]struct {
			result1 fiat.Response
			result2 error
		})
	}
	fake.authorizeReturnsOnCall[i] = struct {
		result1 fiat.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.authorizeMutex.RLock()
	defer fake.authorizeMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ fiat.Client = new(FakeClient)
