// Code generated by counterfeiter. DO NOT EDIT.
package artifactfakes

import (
	"sync"

	"github.com/billiford/go-clouddriver/pkg/artifact"
	"github.com/billiford/go-clouddriver/pkg/helm"
)

type FakeCredentialsController struct {
	ListArtifactCredentialsNamesAndTypesStub        func() []artifact.Credentials
	listArtifactCredentialsNamesAndTypesMutex       sync.RWMutex
	listArtifactCredentialsNamesAndTypesArgsForCall []struct{}
	listArtifactCredentialsNamesAndTypesReturns     struct {
		result1 []artifact.Credentials
	}
	listArtifactCredentialsNamesAndTypesReturnsOnCall map[int]struct {
		result1 []artifact.Credentials
	}
	HelmClientForAccountNameStub        func(string) (helm.Client, error)
	helmClientForAccountNameMutex       sync.RWMutex
	helmClientForAccountNameArgsForCall []struct {
		arg1 string
	}
	helmClientForAccountNameReturns struct {
		result1 helm.Client
		result2 error
	}
	helmClientForAccountNameReturnsOnCall map[int]struct {
		result1 helm.Client
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCredentialsController) ListArtifactCredentialsNamesAndTypes() []artifact.Credentials {
	fake.listArtifactCredentialsNamesAndTypesMutex.Lock()
	ret, specificReturn := fake.listArtifactCredentialsNamesAndTypesReturnsOnCall[len(fake.listArtifactCredentialsNamesAndTypesArgsForCall)]
	fake.listArtifactCredentialsNamesAndTypesArgsForCall = append(fake.listArtifactCredentialsNamesAndTypesArgsForCall, struct{}{})
	fake.recordInvocation("ListArtifactCredentialsNamesAndTypes", []interface{}{})
	fake.listArtifactCredentialsNamesAndTypesMutex.Unlock()
	if fake.ListArtifactCredentialsNamesAndTypesStub != nil {
		return fake.ListArtifactCredentialsNamesAndTypesStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.listArtifactCredentialsNamesAndTypesReturns.result1
}

func (fake *FakeCredentialsController) ListArtifactCredentialsNamesAndTypesCallCount() int {
	fake.listArtifactCredentialsNamesAndTypesMutex.RLock()
	defer fake.listArtifactCredentialsNamesAndTypesMutex.RUnlock()
	return len(fake.listArtifactCredentialsNamesAndTypesArgsForCall)
}

func (fake *FakeCredentialsController) ListArtifactCredentialsNamesAndTypesReturns(result1 []artifact.Credentials) {
	fake.ListArtifactCredentialsNamesAndTypesStub = nil
	fake.listArtifactCredentialsNamesAndTypesReturns = struct {
		result1 []artifact.Credentials
	}{result1}
}

func (fake *FakeCredentialsController) ListArtifactCredentialsNamesAndTypesReturnsOnCall(i int, result1 []artifact.Credentials) {
	fake.ListArtifactCredentialsNamesAndTypesStub = nil
	if fake.listArtifactCredentialsNamesAndTypesReturnsOnCall == nil {
		fake.listArtifactCredentialsNamesAndTypesReturnsOnCall = make(map[int]struct {
			result1 []artifact.Credentials
		})
	}
	fake.listArtifactCredentialsNamesAndTypesReturnsOnCall[i] = struct {
		result1 []artifact.Credentials
	}{result1}
}

func (fake *FakeCredentialsController) HelmClientForAccountName(arg1 string) (helm.Client, error) {
	fake.helmClientForAccountNameMutex.Lock()
	ret, specificReturn := fake.helmClientForAccountNameReturnsOnCall[len(fake.helmClientForAccountNameArgsForCall)]
	fake.helmClientForAccountNameArgsForCall = append(fake.helmClientForAccountNameArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("HelmClientForAccountName", []interface{}{arg1})
	fake.helmClientForAccountNameMutex.Unlock()
	if fake.HelmClientForAccountNameStub != nil {
		return fake.HelmClientForAccountNameStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.helmClientForAccountNameReturns.result1, fake.helmClientForAccountNameReturns.result2
}

func (fake *FakeCredentialsController) HelmClientForAccountNameCallCount() int {
	fake.helmClientForAccountNameMutex.RLock()
	defer fake.helmClientForAccountNameMutex.RUnlock()
	return len(fake.helmClientForAccountNameArgsForCall)
}

func (fake *FakeCredentialsController) HelmClientForAccountNameArgsForCall(i int) string {
	fake.helmClientForAccountNameMutex.RLock()
	defer fake.helmClientForAccountNameMutex.RUnlock()
	return fake.helmClientForAccountNameArgsForCall[i].arg1
}

func (fake *FakeCredentialsController) HelmClientForAccountNameReturns(result1 helm.Client, result2 error) {
	fake.HelmClientForAccountNameStub = nil
	fake.helmClientForAccountNameReturns = struct {
		result1 helm.Client
		result2 error
	}{result1, result2}
}

func (fake *FakeCredentialsController) HelmClientForAccountNameReturnsOnCall(i int, result1 helm.Client, result2 error) {
	fake.HelmClientForAccountNameStub = nil
	if fake.helmClientForAccountNameReturnsOnCall == nil {
		fake.helmClientForAccountNameReturnsOnCall = make(map[int]struct {
			result1 helm.Client
			result2 error
		})
	}
	fake.helmClientForAccountNameReturnsOnCall[i] = struct {
		result1 helm.Client
		result2 error
	}{result1, result2}
}

func (fake *FakeCredentialsController) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.listArtifactCredentialsNamesAndTypesMutex.RLock()
	defer fake.listArtifactCredentialsNamesAndTypesMutex.RUnlock()
	fake.helmClientForAccountNameMutex.RLock()
	defer fake.helmClientForAccountNameMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCredentialsController) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ artifact.CredentialsController = new(FakeCredentialsController)
