// Code generated by counterfeiter. DO NOT EDIT.
package kubernetesfakes

import (
	"sync"

	"github.com/homedepot/go-clouddriver/internal/kubernetes"
)

type FakeClientset struct {
	PodLogsStub        func(string, string, string) (string, error)
	podLogsMutex       sync.RWMutex
	podLogsArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
	}
	podLogsReturns struct {
		result1 string
		result2 error
	}
	podLogsReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClientset) PodLogs(arg1 string, arg2 string, arg3 string) (string, error) {
	fake.podLogsMutex.Lock()
	ret, specificReturn := fake.podLogsReturnsOnCall[len(fake.podLogsArgsForCall)]
	fake.podLogsArgsForCall = append(fake.podLogsArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	fake.recordInvocation("PodLogs", []interface{}{arg1, arg2, arg3})
	fake.podLogsMutex.Unlock()
	if fake.PodLogsStub != nil {
		return fake.PodLogsStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.podLogsReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientset) PodLogsCallCount() int {
	fake.podLogsMutex.RLock()
	defer fake.podLogsMutex.RUnlock()
	return len(fake.podLogsArgsForCall)
}

func (fake *FakeClientset) PodLogsCalls(stub func(string, string, string) (string, error)) {
	fake.podLogsMutex.Lock()
	defer fake.podLogsMutex.Unlock()
	fake.PodLogsStub = stub
}

func (fake *FakeClientset) PodLogsArgsForCall(i int) (string, string, string) {
	fake.podLogsMutex.RLock()
	defer fake.podLogsMutex.RUnlock()
	argsForCall := fake.podLogsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeClientset) PodLogsReturns(result1 string, result2 error) {
	fake.podLogsMutex.Lock()
	defer fake.podLogsMutex.Unlock()
	fake.PodLogsStub = nil
	fake.podLogsReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClientset) PodLogsReturnsOnCall(i int, result1 string, result2 error) {
	fake.podLogsMutex.Lock()
	defer fake.podLogsMutex.Unlock()
	fake.PodLogsStub = nil
	if fake.podLogsReturnsOnCall == nil {
		fake.podLogsReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.podLogsReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClientset) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.podLogsMutex.RLock()
	defer fake.podLogsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClientset) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ kubernetes.Clientset = new(FakeClientset)
