{
 "title": "Go Metrics",
 "description": "Golang Application Runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{namespace=\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"} - go_memstats_other_sys_bytes{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations {pod={{pod}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"} - go_memstats_frees_total{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}[1m])"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}[1m])"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}[1m])"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=~\"^spinnaker$\", pod=~\"(spin-clouddriver-.*)\"}"
    }
   ]
  }
 ]
}