FROM alpine

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY *.go ./

RUN go build cmd/clouddriver/clouddriver.go

COPY clouddriver /usr/local/bin
CMD ["/usr/local/bin/clouddriver"]