// Code generated by counterfeiter. DO NOT EDIT.
package kubernetesfakes

import (
	"sync"

	"github.com/billiford/go-clouddriver/pkg/kubernetes"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

type FakeManifestFilter struct {
	FilterOnClusterStub        func([]unstructured.Unstructured, string) []unstructured.Unstructured
	filterOnClusterMutex       sync.RWMutex
	filterOnClusterArgsForCall []struct {
		arg1 []unstructured.Unstructured
		arg2 string
	}
	filterOnClusterReturns struct {
		result1 []unstructured.Unstructured
	}
	filterOnClusterReturnsOnCall map[int]struct {
		result1 []unstructured.Unstructured
	}
	FilterWhereLabelDoesNotExistStub        func([]unstructured.Unstructured, string) []unstructured.Unstructured
	filterWhereLabelDoesNotExistMutex       sync.RWMutex
	filterWhereLabelDoesNotExistArgsForCall []struct {
		arg1 []unstructured.Unstructured
		arg2 string
	}
	filterWhereLabelDoesNotExistReturns struct {
		result1 []unstructured.Unstructured
	}
	filterWhereLabelDoesNotExistReturnsOnCall map[int]struct {
		result1 []unstructured.Unstructured
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeManifestFilter) FilterOnCluster(arg1 []unstructured.Unstructured, arg2 string) []unstructured.Unstructured {
	var arg1Copy []unstructured.Unstructured
	if arg1 != nil {
		arg1Copy = make([]unstructured.Unstructured, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.filterOnClusterMutex.Lock()
	ret, specificReturn := fake.filterOnClusterReturnsOnCall[len(fake.filterOnClusterArgsForCall)]
	fake.filterOnClusterArgsForCall = append(fake.filterOnClusterArgsForCall, struct {
		arg1 []unstructured.Unstructured
		arg2 string
	}{arg1Copy, arg2})
	fake.recordInvocation("FilterOnCluster", []interface{}{arg1Copy, arg2})
	fake.filterOnClusterMutex.Unlock()
	if fake.FilterOnClusterStub != nil {
		return fake.FilterOnClusterStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.filterOnClusterReturns
	return fakeReturns.result1
}

func (fake *FakeManifestFilter) FilterOnClusterCallCount() int {
	fake.filterOnClusterMutex.RLock()
	defer fake.filterOnClusterMutex.RUnlock()
	return len(fake.filterOnClusterArgsForCall)
}

func (fake *FakeManifestFilter) FilterOnClusterCalls(stub func([]unstructured.Unstructured, string) []unstructured.Unstructured) {
	fake.filterOnClusterMutex.Lock()
	defer fake.filterOnClusterMutex.Unlock()
	fake.FilterOnClusterStub = stub
}

func (fake *FakeManifestFilter) FilterOnClusterArgsForCall(i int) ([]unstructured.Unstructured, string) {
	fake.filterOnClusterMutex.RLock()
	defer fake.filterOnClusterMutex.RUnlock()
	argsForCall := fake.filterOnClusterArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeManifestFilter) FilterOnClusterReturns(result1 []unstructured.Unstructured) {
	fake.filterOnClusterMutex.Lock()
	defer fake.filterOnClusterMutex.Unlock()
	fake.FilterOnClusterStub = nil
	fake.filterOnClusterReturns = struct {
		result1 []unstructured.Unstructured
	}{result1}
}

func (fake *FakeManifestFilter) FilterOnClusterReturnsOnCall(i int, result1 []unstructured.Unstructured) {
	fake.filterOnClusterMutex.Lock()
	defer fake.filterOnClusterMutex.Unlock()
	fake.FilterOnClusterStub = nil
	if fake.filterOnClusterReturnsOnCall == nil {
		fake.filterOnClusterReturnsOnCall = make(map[int]struct {
			result1 []unstructured.Unstructured
		})
	}
	fake.filterOnClusterReturnsOnCall[i] = struct {
		result1 []unstructured.Unstructured
	}{result1}
}

func (fake *FakeManifestFilter) FilterWhereLabelDoesNotExist(arg1 []unstructured.Unstructured, arg2 string) []unstructured.Unstructured {
	var arg1Copy []unstructured.Unstructured
	if arg1 != nil {
		arg1Copy = make([]unstructured.Unstructured, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.filterWhereLabelDoesNotExistMutex.Lock()
	ret, specificReturn := fake.filterWhereLabelDoesNotExistReturnsOnCall[len(fake.filterWhereLabelDoesNotExistArgsForCall)]
	fake.filterWhereLabelDoesNotExistArgsForCall = append(fake.filterWhereLabelDoesNotExistArgsForCall, struct {
		arg1 []unstructured.Unstructured
		arg2 string
	}{arg1Copy, arg2})
	fake.recordInvocation("FilterWhereLabelDoesNotExist", []interface{}{arg1Copy, arg2})
	fake.filterWhereLabelDoesNotExistMutex.Unlock()
	if fake.FilterWhereLabelDoesNotExistStub != nil {
		return fake.FilterWhereLabelDoesNotExistStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.filterWhereLabelDoesNotExistReturns
	return fakeReturns.result1
}

func (fake *FakeManifestFilter) FilterWhereLabelDoesNotExistCallCount() int {
	fake.filterWhereLabelDoesNotExistMutex.RLock()
	defer fake.filterWhereLabelDoesNotExistMutex.RUnlock()
	return len(fake.filterWhereLabelDoesNotExistArgsForCall)
}

func (fake *FakeManifestFilter) FilterWhereLabelDoesNotExistCalls(stub func([]unstructured.Unstructured, string) []unstructured.Unstructured) {
	fake.filterWhereLabelDoesNotExistMutex.Lock()
	defer fake.filterWhereLabelDoesNotExistMutex.Unlock()
	fake.FilterWhereLabelDoesNotExistStub = stub
}

func (fake *FakeManifestFilter) FilterWhereLabelDoesNotExistArgsForCall(i int) ([]unstructured.Unstructured, string) {
	fake.filterWhereLabelDoesNotExistMutex.RLock()
	defer fake.filterWhereLabelDoesNotExistMutex.RUnlock()
	argsForCall := fake.filterWhereLabelDoesNotExistArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeManifestFilter) FilterWhereLabelDoesNotExistReturns(result1 []unstructured.Unstructured) {
	fake.filterWhereLabelDoesNotExistMutex.Lock()
	defer fake.filterWhereLabelDoesNotExistMutex.Unlock()
	fake.FilterWhereLabelDoesNotExistStub = nil
	fake.filterWhereLabelDoesNotExistReturns = struct {
		result1 []unstructured.Unstructured
	}{result1}
}

func (fake *FakeManifestFilter) FilterWhereLabelDoesNotExistReturnsOnCall(i int, result1 []unstructured.Unstructured) {
	fake.filterWhereLabelDoesNotExistMutex.Lock()
	defer fake.filterWhereLabelDoesNotExistMutex.Unlock()
	fake.FilterWhereLabelDoesNotExistStub = nil
	if fake.filterWhereLabelDoesNotExistReturnsOnCall == nil {
		fake.filterWhereLabelDoesNotExistReturnsOnCall = make(map[int]struct {
			result1 []unstructured.Unstructured
		})
	}
	fake.filterWhereLabelDoesNotExistReturnsOnCall[i] = struct {
		result1 []unstructured.Unstructured
	}{result1}
}

func (fake *FakeManifestFilter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.filterOnClusterMutex.RLock()
	defer fake.filterOnClusterMutex.RUnlock()
	fake.filterWhereLabelDoesNotExistMutex.RLock()
	defer fake.filterWhereLabelDoesNotExistMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeManifestFilter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ kubernetes.ManifestFilter = new(FakeManifestFilter)
