// Code generated by counterfeiter. DO NOT EDIT.
package sqlfakes

import (
	"sync"

	"github.com/homedepot/go-clouddriver/internal/kubernetes"
	"github.com/homedepot/go-clouddriver/internal/sql"
	"gorm.io/gorm"
)

type FakeClient struct {
	ConnectStub        func() error
	connectMutex       sync.RWMutex
	connectArgsForCall []struct {
	}
	connectReturns struct {
		result1 error
	}
	connectReturnsOnCall map[int]struct {
		result1 error
	}
	CreateKubernetesProviderStub        func(kubernetes.Provider) error
	createKubernetesProviderMutex       sync.RWMutex
	createKubernetesProviderArgsForCall []struct {
		arg1 kubernetes.Provider
	}
	createKubernetesProviderReturns struct {
		result1 error
	}
	createKubernetesProviderReturnsOnCall map[int]struct {
		result1 error
	}
	CreateKubernetesResourceStub        func(kubernetes.Resource) error
	createKubernetesResourceMutex       sync.RWMutex
	createKubernetesResourceArgsForCall []struct {
		arg1 kubernetes.Resource
	}
	createKubernetesResourceReturns struct {
		result1 error
	}
	createKubernetesResourceReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteKubernetesProviderStub        func(string) error
	deleteKubernetesProviderMutex       sync.RWMutex
	deleteKubernetesProviderArgsForCall []struct {
		arg1 string
	}
	deleteKubernetesProviderReturns struct {
		result1 error
	}
	deleteKubernetesProviderReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteKubernetesResourcesByAccountNameStub        func(string) error
	deleteKubernetesResourcesByAccountNameMutex       sync.RWMutex
	deleteKubernetesResourcesByAccountNameArgsForCall []struct {
		arg1 string
	}
	deleteKubernetesResourcesByAccountNameReturns struct {
		result1 error
	}
	deleteKubernetesResourcesByAccountNameReturnsOnCall map[int]struct {
		result1 error
	}
	GetKubernetesProviderStub        func(string) (kubernetes.Provider, error)
	getKubernetesProviderMutex       sync.RWMutex
	getKubernetesProviderArgsForCall []struct {
		arg1 string
	}
	getKubernetesProviderReturns struct {
		result1 kubernetes.Provider
		result2 error
	}
	getKubernetesProviderReturnsOnCall map[int]struct {
		result1 kubernetes.Provider
		result2 error
	}
	GetKubernetesProviderAndPermissionsStub        func(string) (kubernetes.Provider, error)
	getKubernetesProviderAndPermissionsMutex       sync.RWMutex
	getKubernetesProviderAndPermissionsArgsForCall []struct {
		arg1 string
	}
	getKubernetesProviderAndPermissionsReturns struct {
		result1 kubernetes.Provider
		result2 error
	}
	getKubernetesProviderAndPermissionsReturnsOnCall map[int]struct {
		result1 kubernetes.Provider
		result2 error
	}
	ListKubernetesAccountsBySpinnakerAppStub        func(string) ([]string, error)
	listKubernetesAccountsBySpinnakerAppMutex       sync.RWMutex
	listKubernetesAccountsBySpinnakerAppArgsForCall []struct {
		arg1 string
	}
	listKubernetesAccountsBySpinnakerAppReturns struct {
		result1 []string
		result2 error
	}
	listKubernetesAccountsBySpinnakerAppReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	ListKubernetesClustersByApplicationStub        func(string) ([]kubernetes.Resource, error)
	listKubernetesClustersByApplicationMutex       sync.RWMutex
	listKubernetesClustersByApplicationArgsForCall []struct {
		arg1 string
	}
	listKubernetesClustersByApplicationReturns struct {
		result1 []kubernetes.Resource
		result2 error
	}
	listKubernetesClustersByApplicationReturnsOnCall map[int]struct {
		result1 []kubernetes.Resource
		result2 error
	}
	ListKubernetesClustersByFieldsStub        func(...string) ([]kubernetes.Resource, error)
	listKubernetesClustersByFieldsMutex       sync.RWMutex
	listKubernetesClustersByFieldsArgsForCall []struct {
		arg1 []string
	}
	listKubernetesClustersByFieldsReturns struct {
		result1 []kubernetes.Resource
		result2 error
	}
	listKubernetesClustersByFieldsReturnsOnCall map[int]struct {
		result1 []kubernetes.Resource
		result2 error
	}
	ListKubernetesProvidersStub        func() ([]kubernetes.Provider, error)
	listKubernetesProvidersMutex       sync.RWMutex
	listKubernetesProvidersArgsForCall []struct {
	}
	listKubernetesProvidersReturns struct {
		result1 []kubernetes.Provider
		result2 error
	}
	listKubernetesProvidersReturnsOnCall map[int]struct {
		result1 []kubernetes.Provider
		result2 error
	}
	ListKubernetesProvidersAndPermissionsStub        func() ([]kubernetes.Provider, error)
	listKubernetesProvidersAndPermissionsMutex       sync.RWMutex
	listKubernetesProvidersAndPermissionsArgsForCall []struct {
	}
	listKubernetesProvidersAndPermissionsReturns struct {
		result1 []kubernetes.Provider
		result2 error
	}
	listKubernetesProvidersAndPermissionsReturnsOnCall map[int]struct {
		result1 []kubernetes.Provider
		result2 error
	}
	ListKubernetesResourcesByFieldsStub        func(...string) ([]kubernetes.Resource, error)
	listKubernetesResourcesByFieldsMutex       sync.RWMutex
	listKubernetesResourcesByFieldsArgsForCall []struct {
		arg1 []string
	}
	listKubernetesResourcesByFieldsReturns struct {
		result1 []kubernetes.Resource
		result2 error
	}
	listKubernetesResourcesByFieldsReturnsOnCall map[int]struct {
		result1 []kubernetes.Resource
		result2 error
	}
	ListKubernetesResourcesByTaskIDStub        func(string) ([]kubernetes.Resource, error)
	listKubernetesResourcesByTaskIDMutex       sync.RWMutex
	listKubernetesResourcesByTaskIDArgsForCall []struct {
		arg1 string
	}
	listKubernetesResourcesByTaskIDReturns struct {
		result1 []kubernetes.Resource
		result2 error
	}
	listKubernetesResourcesByTaskIDReturnsOnCall map[int]struct {
		result1 []kubernetes.Resource
		result2 error
	}
	ListReadGroupsByAccountNameStub        func(string) ([]string, error)
	listReadGroupsByAccountNameMutex       sync.RWMutex
	listReadGroupsByAccountNameArgsForCall []struct {
		arg1 string
	}
	listReadGroupsByAccountNameReturns struct {
		result1 []string
		result2 error
	}
	listReadGroupsByAccountNameReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	ListWriteGroupsByAccountNameStub        func(string) ([]string, error)
	listWriteGroupsByAccountNameMutex       sync.RWMutex
	listWriteGroupsByAccountNameArgsForCall []struct {
		arg1 string
	}
	listWriteGroupsByAccountNameReturns struct {
		result1 []string
		result2 error
	}
	listWriteGroupsByAccountNameReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	WithConfigStub        func(*gorm.Config)
	withConfigMutex       sync.RWMutex
	withConfigArgsForCall []struct {
		arg1 *gorm.Config
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) Connect() error {
	fake.connectMutex.Lock()
	ret, specificReturn := fake.connectReturnsOnCall[len(fake.connectArgsForCall)]
	fake.connectArgsForCall = append(fake.connectArgsForCall, struct {
	}{})
	stub := fake.ConnectStub
	fakeReturns := fake.connectReturns
	fake.recordInvocation("Connect", []interface{}{})
	fake.connectMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) ConnectCallCount() int {
	fake.connectMutex.RLock()
	defer fake.connectMutex.RUnlock()
	return len(fake.connectArgsForCall)
}

func (fake *FakeClient) ConnectCalls(stub func() error) {
	fake.connectMutex.Lock()
	defer fake.connectMutex.Unlock()
	fake.ConnectStub = stub
}

func (fake *FakeClient) ConnectReturns(result1 error) {
	fake.connectMutex.Lock()
	defer fake.connectMutex.Unlock()
	fake.ConnectStub = nil
	fake.connectReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) ConnectReturnsOnCall(i int, result1 error) {
	fake.connectMutex.Lock()
	defer fake.connectMutex.Unlock()
	fake.ConnectStub = nil
	if fake.connectReturnsOnCall == nil {
		fake.connectReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.connectReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) CreateKubernetesProvider(arg1 kubernetes.Provider) error {
	fake.createKubernetesProviderMutex.Lock()
	ret, specificReturn := fake.createKubernetesProviderReturnsOnCall[len(fake.createKubernetesProviderArgsForCall)]
	fake.createKubernetesProviderArgsForCall = append(fake.createKubernetesProviderArgsForCall, struct {
		arg1 kubernetes.Provider
	}{arg1})
	stub := fake.CreateKubernetesProviderStub
	fakeReturns := fake.createKubernetesProviderReturns
	fake.recordInvocation("CreateKubernetesProvider", []interface{}{arg1})
	fake.createKubernetesProviderMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) CreateKubernetesProviderCallCount() int {
	fake.createKubernetesProviderMutex.RLock()
	defer fake.createKubernetesProviderMutex.RUnlock()
	return len(fake.createKubernetesProviderArgsForCall)
}

func (fake *FakeClient) CreateKubernetesProviderCalls(stub func(kubernetes.Provider) error) {
	fake.createKubernetesProviderMutex.Lock()
	defer fake.createKubernetesProviderMutex.Unlock()
	fake.CreateKubernetesProviderStub = stub
}

func (fake *FakeClient) CreateKubernetesProviderArgsForCall(i int) kubernetes.Provider {
	fake.createKubernetesProviderMutex.RLock()
	defer fake.createKubernetesProviderMutex.RUnlock()
	argsForCall := fake.createKubernetesProviderArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) CreateKubernetesProviderReturns(result1 error) {
	fake.createKubernetesProviderMutex.Lock()
	defer fake.createKubernetesProviderMutex.Unlock()
	fake.CreateKubernetesProviderStub = nil
	fake.createKubernetesProviderReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) CreateKubernetesProviderReturnsOnCall(i int, result1 error) {
	fake.createKubernetesProviderMutex.Lock()
	defer fake.createKubernetesProviderMutex.Unlock()
	fake.CreateKubernetesProviderStub = nil
	if fake.createKubernetesProviderReturnsOnCall == nil {
		fake.createKubernetesProviderReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createKubernetesProviderReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) CreateKubernetesResource(arg1 kubernetes.Resource) error {
	fake.createKubernetesResourceMutex.Lock()
	ret, specificReturn := fake.createKubernetesResourceReturnsOnCall[len(fake.createKubernetesResourceArgsForCall)]
	fake.createKubernetesResourceArgsForCall = append(fake.createKubernetesResourceArgsForCall, struct {
		arg1 kubernetes.Resource
	}{arg1})
	stub := fake.CreateKubernetesResourceStub
	fakeReturns := fake.createKubernetesResourceReturns
	fake.recordInvocation("CreateKubernetesResource", []interface{}{arg1})
	fake.createKubernetesResourceMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) CreateKubernetesResourceCallCount() int {
	fake.createKubernetesResourceMutex.RLock()
	defer fake.createKubernetesResourceMutex.RUnlock()
	return len(fake.createKubernetesResourceArgsForCall)
}

func (fake *FakeClient) CreateKubernetesResourceCalls(stub func(kubernetes.Resource) error) {
	fake.createKubernetesResourceMutex.Lock()
	defer fake.createKubernetesResourceMutex.Unlock()
	fake.CreateKubernetesResourceStub = stub
}

func (fake *FakeClient) CreateKubernetesResourceArgsForCall(i int) kubernetes.Resource {
	fake.createKubernetesResourceMutex.RLock()
	defer fake.createKubernetesResourceMutex.RUnlock()
	argsForCall := fake.createKubernetesResourceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) CreateKubernetesResourceReturns(result1 error) {
	fake.createKubernetesResourceMutex.Lock()
	defer fake.createKubernetesResourceMutex.Unlock()
	fake.CreateKubernetesResourceStub = nil
	fake.createKubernetesResourceReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) CreateKubernetesResourceReturnsOnCall(i int, result1 error) {
	fake.createKubernetesResourceMutex.Lock()
	defer fake.createKubernetesResourceMutex.Unlock()
	fake.CreateKubernetesResourceStub = nil
	if fake.createKubernetesResourceReturnsOnCall == nil {
		fake.createKubernetesResourceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createKubernetesResourceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) DeleteKubernetesProvider(arg1 string) error {
	fake.deleteKubernetesProviderMutex.Lock()
	ret, specificReturn := fake.deleteKubernetesProviderReturnsOnCall[len(fake.deleteKubernetesProviderArgsForCall)]
	fake.deleteKubernetesProviderArgsForCall = append(fake.deleteKubernetesProviderArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.DeleteKubernetesProviderStub
	fakeReturns := fake.deleteKubernetesProviderReturns
	fake.recordInvocation("DeleteKubernetesProvider", []interface{}{arg1})
	fake.deleteKubernetesProviderMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) DeleteKubernetesProviderCallCount() int {
	fake.deleteKubernetesProviderMutex.RLock()
	defer fake.deleteKubernetesProviderMutex.RUnlock()
	return len(fake.deleteKubernetesProviderArgsForCall)
}

func (fake *FakeClient) DeleteKubernetesProviderCalls(stub func(string) error) {
	fake.deleteKubernetesProviderMutex.Lock()
	defer fake.deleteKubernetesProviderMutex.Unlock()
	fake.DeleteKubernetesProviderStub = stub
}

func (fake *FakeClient) DeleteKubernetesProviderArgsForCall(i int) string {
	fake.deleteKubernetesProviderMutex.RLock()
	defer fake.deleteKubernetesProviderMutex.RUnlock()
	argsForCall := fake.deleteKubernetesProviderArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) DeleteKubernetesProviderReturns(result1 error) {
	fake.deleteKubernetesProviderMutex.Lock()
	defer fake.deleteKubernetesProviderMutex.Unlock()
	fake.DeleteKubernetesProviderStub = nil
	fake.deleteKubernetesProviderReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) DeleteKubernetesProviderReturnsOnCall(i int, result1 error) {
	fake.deleteKubernetesProviderMutex.Lock()
	defer fake.deleteKubernetesProviderMutex.Unlock()
	fake.DeleteKubernetesProviderStub = nil
	if fake.deleteKubernetesProviderReturnsOnCall == nil {
		fake.deleteKubernetesProviderReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteKubernetesProviderReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) DeleteKubernetesResourcesByAccountName(arg1 string) error {
	fake.deleteKubernetesResourcesByAccountNameMutex.Lock()
	ret, specificReturn := fake.deleteKubernetesResourcesByAccountNameReturnsOnCall[len(fake.deleteKubernetesResourcesByAccountNameArgsForCall)]
	fake.deleteKubernetesResourcesByAccountNameArgsForCall = append(fake.deleteKubernetesResourcesByAccountNameArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.DeleteKubernetesResourcesByAccountNameStub
	fakeReturns := fake.deleteKubernetesResourcesByAccountNameReturns
	fake.recordInvocation("DeleteKubernetesResourcesByAccountName", []interface{}{arg1})
	fake.deleteKubernetesResourcesByAccountNameMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) DeleteKubernetesResourcesByAccountNameCallCount() int {
	fake.deleteKubernetesResourcesByAccountNameMutex.RLock()
	defer fake.deleteKubernetesResourcesByAccountNameMutex.RUnlock()
	return len(fake.deleteKubernetesResourcesByAccountNameArgsForCall)
}

func (fake *FakeClient) DeleteKubernetesResourcesByAccountNameCalls(stub func(string) error) {
	fake.deleteKubernetesResourcesByAccountNameMutex.Lock()
	defer fake.deleteKubernetesResourcesByAccountNameMutex.Unlock()
	fake.DeleteKubernetesResourcesByAccountNameStub = stub
}

func (fake *FakeClient) DeleteKubernetesResourcesByAccountNameArgsForCall(i int) string {
	fake.deleteKubernetesResourcesByAccountNameMutex.RLock()
	defer fake.deleteKubernetesResourcesByAccountNameMutex.RUnlock()
	argsForCall := fake.deleteKubernetesResourcesByAccountNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) DeleteKubernetesResourcesByAccountNameReturns(result1 error) {
	fake.deleteKubernetesResourcesByAccountNameMutex.Lock()
	defer fake.deleteKubernetesResourcesByAccountNameMutex.Unlock()
	fake.DeleteKubernetesResourcesByAccountNameStub = nil
	fake.deleteKubernetesResourcesByAccountNameReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) DeleteKubernetesResourcesByAccountNameReturnsOnCall(i int, result1 error) {
	fake.deleteKubernetesResourcesByAccountNameMutex.Lock()
	defer fake.deleteKubernetesResourcesByAccountNameMutex.Unlock()
	fake.DeleteKubernetesResourcesByAccountNameStub = nil
	if fake.deleteKubernetesResourcesByAccountNameReturnsOnCall == nil {
		fake.deleteKubernetesResourcesByAccountNameReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteKubernetesResourcesByAccountNameReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) GetKubernetesProvider(arg1 string) (kubernetes.Provider, error) {
	fake.getKubernetesProviderMutex.Lock()
	ret, specificReturn := fake.getKubernetesProviderReturnsOnCall[len(fake.getKubernetesProviderArgsForCall)]
	fake.getKubernetesProviderArgsForCall = append(fake.getKubernetesProviderArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetKubernetesProviderStub
	fakeReturns := fake.getKubernetesProviderReturns
	fake.recordInvocation("GetKubernetesProvider", []interface{}{arg1})
	fake.getKubernetesProviderMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) GetKubernetesProviderCallCount() int {
	fake.getKubernetesProviderMutex.RLock()
	defer fake.getKubernetesProviderMutex.RUnlock()
	return len(fake.getKubernetesProviderArgsForCall)
}

func (fake *FakeClient) GetKubernetesProviderCalls(stub func(string) (kubernetes.Provider, error)) {
	fake.getKubernetesProviderMutex.Lock()
	defer fake.getKubernetesProviderMutex.Unlock()
	fake.GetKubernetesProviderStub = stub
}

func (fake *FakeClient) GetKubernetesProviderArgsForCall(i int) string {
	fake.getKubernetesProviderMutex.RLock()
	defer fake.getKubernetesProviderMutex.RUnlock()
	argsForCall := fake.getKubernetesProviderArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) GetKubernetesProviderReturns(result1 kubernetes.Provider, result2 error) {
	fake.getKubernetesProviderMutex.Lock()
	defer fake.getKubernetesProviderMutex.Unlock()
	fake.GetKubernetesProviderStub = nil
	fake.getKubernetesProviderReturns = struct {
		result1 kubernetes.Provider
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetKubernetesProviderReturnsOnCall(i int, result1 kubernetes.Provider, result2 error) {
	fake.getKubernetesProviderMutex.Lock()
	defer fake.getKubernetesProviderMutex.Unlock()
	fake.GetKubernetesProviderStub = nil
	if fake.getKubernetesProviderReturnsOnCall == nil {
		fake.getKubernetesProviderReturnsOnCall = make(map[int]struct {
			result1 kubernetes.Provider
			result2 error
		})
	}
	fake.getKubernetesProviderReturnsOnCall[i] = struct {
		result1 kubernetes.Provider
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetKubernetesProviderAndPermissions(arg1 string) (kubernetes.Provider, error) {
	fake.getKubernetesProviderAndPermissionsMutex.Lock()
	ret, specificReturn := fake.getKubernetesProviderAndPermissionsReturnsOnCall[len(fake.getKubernetesProviderAndPermissionsArgsForCall)]
	fake.getKubernetesProviderAndPermissionsArgsForCall = append(fake.getKubernetesProviderAndPermissionsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetKubernetesProviderAndPermissionsStub
	fakeReturns := fake.getKubernetesProviderAndPermissionsReturns
	fake.recordInvocation("GetKubernetesProviderAndPermissions", []interface{}{arg1})
	fake.getKubernetesProviderAndPermissionsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) GetKubernetesProviderAndPermissionsCallCount() int {
	fake.getKubernetesProviderAndPermissionsMutex.RLock()
	defer fake.getKubernetesProviderAndPermissionsMutex.RUnlock()
	return len(fake.getKubernetesProviderAndPermissionsArgsForCall)
}

func (fake *FakeClient) GetKubernetesProviderAndPermissionsCalls(stub func(string) (kubernetes.Provider, error)) {
	fake.getKubernetesProviderAndPermissionsMutex.Lock()
	defer fake.getKubernetesProviderAndPermissionsMutex.Unlock()
	fake.GetKubernetesProviderAndPermissionsStub = stub
}

func (fake *FakeClient) GetKubernetesProviderAndPermissionsArgsForCall(i int) string {
	fake.getKubernetesProviderAndPermissionsMutex.RLock()
	defer fake.getKubernetesProviderAndPermissionsMutex.RUnlock()
	argsForCall := fake.getKubernetesProviderAndPermissionsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) GetKubernetesProviderAndPermissionsReturns(result1 kubernetes.Provider, result2 error) {
	fake.getKubernetesProviderAndPermissionsMutex.Lock()
	defer fake.getKubernetesProviderAndPermissionsMutex.Unlock()
	fake.GetKubernetesProviderAndPermissionsStub = nil
	fake.getKubernetesProviderAndPermissionsReturns = struct {
		result1 kubernetes.Provider
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetKubernetesProviderAndPermissionsReturnsOnCall(i int, result1 kubernetes.Provider, result2 error) {
	fake.getKubernetesProviderAndPermissionsMutex.Lock()
	defer fake.getKubernetesProviderAndPermissionsMutex.Unlock()
	fake.GetKubernetesProviderAndPermissionsStub = nil
	if fake.getKubernetesProviderAndPermissionsReturnsOnCall == nil {
		fake.getKubernetesProviderAndPermissionsReturnsOnCall = make(map[int]struct {
			result1 kubernetes.Provider
			result2 error
		})
	}
	fake.getKubernetesProviderAndPermissionsReturnsOnCall[i] = struct {
		result1 kubernetes.Provider
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListKubernetesAccountsBySpinnakerApp(arg1 string) ([]string, error) {
	fake.listKubernetesAccountsBySpinnakerAppMutex.Lock()
	ret, specificReturn := fake.listKubernetesAccountsBySpinnakerAppReturnsOnCall[len(fake.listKubernetesAccountsBySpinnakerAppArgsForCall)]
	fake.listKubernetesAccountsBySpinnakerAppArgsForCall = append(fake.listKubernetesAccountsBySpinnakerAppArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ListKubernetesAccountsBySpinnakerAppStub
	fakeReturns := fake.listKubernetesAccountsBySpinnakerAppReturns
	fake.recordInvocation("ListKubernetesAccountsBySpinnakerApp", []interface{}{arg1})
	fake.listKubernetesAccountsBySpinnakerAppMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) ListKubernetesAccountsBySpinnakerAppCallCount() int {
	fake.listKubernetesAccountsBySpinnakerAppMutex.RLock()
	defer fake.listKubernetesAccountsBySpinnakerAppMutex.RUnlock()
	return len(fake.listKubernetesAccountsBySpinnakerAppArgsForCall)
}

func (fake *FakeClient) ListKubernetesAccountsBySpinnakerAppCalls(stub func(string) ([]string, error)) {
	fake.listKubernetesAccountsBySpinnakerAppMutex.Lock()
	defer fake.listKubernetesAccountsBySpinnakerAppMutex.Unlock()
	fake.ListKubernetesAccountsBySpinnakerAppStub = stub
}

func (fake *FakeClient) ListKubernetesAccountsBySpinnakerAppArgsForCall(i int) string {
	fake.listKubernetesAccountsBySpinnakerAppMutex.RLock()
	defer fake.listKubernetesAccountsBySpinnakerAppMutex.RUnlock()
	argsForCall := fake.listKubernetesAccountsBySpinnakerAppArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) ListKubernetesAccountsBySpinnakerAppReturns(result1 []string, result2 error) {
	fake.listKubernetesAccountsBySpinnakerAppMutex.Lock()
	defer fake.listKubernetesAccountsBySpinnakerAppMutex.Unlock()
	fake.ListKubernetesAccountsBySpinnakerAppStub = nil
	fake.listKubernetesAccountsBySpinnakerAppReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListKubernetesAccountsBySpinnakerAppReturnsOnCall(i int, result1 []string, result2 error) {
	fake.listKubernetesAccountsBySpinnakerAppMutex.Lock()
	defer fake.listKubernetesAccountsBySpinnakerAppMutex.Unlock()
	fake.ListKubernetesAccountsBySpinnakerAppStub = nil
	if fake.listKubernetesAccountsBySpinnakerAppReturnsOnCall == nil {
		fake.listKubernetesAccountsBySpinnakerAppReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.listKubernetesAccountsBySpinnakerAppReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListKubernetesClustersByApplication(arg1 string) ([]kubernetes.Resource, error) {
	fake.listKubernetesClustersByApplicationMutex.Lock()
	ret, specificReturn := fake.listKubernetesClustersByApplicationReturnsOnCall[len(fake.listKubernetesClustersByApplicationArgsForCall)]
	fake.listKubernetesClustersByApplicationArgsForCall = append(fake.listKubernetesClustersByApplicationArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ListKubernetesClustersByApplicationStub
	fakeReturns := fake.listKubernetesClustersByApplicationReturns
	fake.recordInvocation("ListKubernetesClustersByApplication", []interface{}{arg1})
	fake.listKubernetesClustersByApplicationMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) ListKubernetesClustersByApplicationCallCount() int {
	fake.listKubernetesClustersByApplicationMutex.RLock()
	defer fake.listKubernetesClustersByApplicationMutex.RUnlock()
	return len(fake.listKubernetesClustersByApplicationArgsForCall)
}

func (fake *FakeClient) ListKubernetesClustersByApplicationCalls(stub func(string) ([]kubernetes.Resource, error)) {
	fake.listKubernetesClustersByApplicationMutex.Lock()
	defer fake.listKubernetesClustersByApplicationMutex.Unlock()
	fake.ListKubernetesClustersByApplicationStub = stub
}

func (fake *FakeClient) ListKubernetesClustersByApplicationArgsForCall(i int) string {
	fake.listKubernetesClustersByApplicationMutex.RLock()
	defer fake.listKubernetesClustersByApplicationMutex.RUnlock()
	argsForCall := fake.listKubernetesClustersByApplicationArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) ListKubernetesClustersByApplicationReturns(result1 []kubernetes.Resource, result2 error) {
	fake.listKubernetesClustersByApplicationMutex.Lock()
	defer fake.listKubernetesClustersByApplicationMutex.Unlock()
	fake.ListKubernetesClustersByApplicationStub = nil
	fake.listKubernetesClustersByApplicationReturns = struct {
		result1 []kubernetes.Resource
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListKubernetesClustersByApplicationReturnsOnCall(i int, result1 []kubernetes.Resource, result2 error) {
	fake.listKubernetesClustersByApplicationMutex.Lock()
	defer fake.listKubernetesClustersByApplicationMutex.Unlock()
	fake.ListKubernetesClustersByApplicationStub = nil
	if fake.listKubernetesClustersByApplicationReturnsOnCall == nil {
		fake.listKubernetesClustersByApplicationReturnsOnCall = make(map[int]struct {
			result1 []kubernetes.Resource
			result2 error
		})
	}
	fake.listKubernetesClustersByApplicationReturnsOnCall[i] = struct {
		result1 []kubernetes.Resource
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListKubernetesClustersByFields(arg1 ...string) ([]kubernetes.Resource, error) {
	fake.listKubernetesClustersByFieldsMutex.Lock()
	ret, specificReturn := fake.listKubernetesClustersByFieldsReturnsOnCall[len(fake.listKubernetesClustersByFieldsArgsForCall)]
	fake.listKubernetesClustersByFieldsArgsForCall = append(fake.listKubernetesClustersByFieldsArgsForCall, struct {
		arg1 []string
	}{arg1})
	stub := fake.ListKubernetesClustersByFieldsStub
	fakeReturns := fake.listKubernetesClustersByFieldsReturns
	fake.recordInvocation("ListKubernetesClustersByFields", []interface{}{arg1})
	fake.listKubernetesClustersByFieldsMutex.Unlock()
	if stub != nil {
		return stub(arg1...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) ListKubernetesClustersByFieldsCallCount() int {
	fake.listKubernetesClustersByFieldsMutex.RLock()
	defer fake.listKubernetesClustersByFieldsMutex.RUnlock()
	return len(fake.listKubernetesClustersByFieldsArgsForCall)
}

func (fake *FakeClient) ListKubernetesClustersByFieldsCalls(stub func(...string) ([]kubernetes.Resource, error)) {
	fake.listKubernetesClustersByFieldsMutex.Lock()
	defer fake.listKubernetesClustersByFieldsMutex.Unlock()
	fake.ListKubernetesClustersByFieldsStub = stub
}

func (fake *FakeClient) ListKubernetesClustersByFieldsArgsForCall(i int) []string {
	fake.listKubernetesClustersByFieldsMutex.RLock()
	defer fake.listKubernetesClustersByFieldsMutex.RUnlock()
	argsForCall := fake.listKubernetesClustersByFieldsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) ListKubernetesClustersByFieldsReturns(result1 []kubernetes.Resource, result2 error) {
	fake.listKubernetesClustersByFieldsMutex.Lock()
	defer fake.listKubernetesClustersByFieldsMutex.Unlock()
	fake.ListKubernetesClustersByFieldsStub = nil
	fake.listKubernetesClustersByFieldsReturns = struct {
		result1 []kubernetes.Resource
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListKubernetesClustersByFieldsReturnsOnCall(i int, result1 []kubernetes.Resource, result2 error) {
	fake.listKubernetesClustersByFieldsMutex.Lock()
	defer fake.listKubernetesClustersByFieldsMutex.Unlock()
	fake.ListKubernetesClustersByFieldsStub = nil
	if fake.listKubernetesClustersByFieldsReturnsOnCall == nil {
		fake.listKubernetesClustersByFieldsReturnsOnCall = make(map[int]struct {
			result1 []kubernetes.Resource
			result2 error
		})
	}
	fake.listKubernetesClustersByFieldsReturnsOnCall[i] = struct {
		result1 []kubernetes.Resource
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListKubernetesProviders() ([]kubernetes.Provider, error) {
	fake.listKubernetesProvidersMutex.Lock()
	ret, specificReturn := fake.listKubernetesProvidersReturnsOnCall[len(fake.listKubernetesProvidersArgsForCall)]
	fake.listKubernetesProvidersArgsForCall = append(fake.listKubernetesProvidersArgsForCall, struct {
	}{})
	stub := fake.ListKubernetesProvidersStub
	fakeReturns := fake.listKubernetesProvidersReturns
	fake.recordInvocation("ListKubernetesProviders", []interface{}{})
	fake.listKubernetesProvidersMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) ListKubernetesProvidersCallCount() int {
	fake.listKubernetesProvidersMutex.RLock()
	defer fake.listKubernetesProvidersMutex.RUnlock()
	return len(fake.listKubernetesProvidersArgsForCall)
}

func (fake *FakeClient) ListKubernetesProvidersCalls(stub func() ([]kubernetes.Provider, error)) {
	fake.listKubernetesProvidersMutex.Lock()
	defer fake.listKubernetesProvidersMutex.Unlock()
	fake.ListKubernetesProvidersStub = stub
}

func (fake *FakeClient) ListKubernetesProvidersReturns(result1 []kubernetes.Provider, result2 error) {
	fake.listKubernetesProvidersMutex.Lock()
	defer fake.listKubernetesProvidersMutex.Unlock()
	fake.ListKubernetesProvidersStub = nil
	fake.listKubernetesProvidersReturns = struct {
		result1 []kubernetes.Provider
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListKubernetesProvidersReturnsOnCall(i int, result1 []kubernetes.Provider, result2 error) {
	fake.listKubernetesProvidersMutex.Lock()
	defer fake.listKubernetesProvidersMutex.Unlock()
	fake.ListKubernetesProvidersStub = nil
	if fake.listKubernetesProvidersReturnsOnCall == nil {
		fake.listKubernetesProvidersReturnsOnCall = make(map[int]struct {
			result1 []kubernetes.Provider
			result2 error
		})
	}
	fake.listKubernetesProvidersReturnsOnCall[i] = struct {
		result1 []kubernetes.Provider
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListKubernetesProvidersAndPermissions() ([]kubernetes.Provider, error) {
	fake.listKubernetesProvidersAndPermissionsMutex.Lock()
	ret, specificReturn := fake.listKubernetesProvidersAndPermissionsReturnsOnCall[len(fake.listKubernetesProvidersAndPermissionsArgsForCall)]
	fake.listKubernetesProvidersAndPermissionsArgsForCall = append(fake.listKubernetesProvidersAndPermissionsArgsForCall, struct {
	}{})
	stub := fake.ListKubernetesProvidersAndPermissionsStub
	fakeReturns := fake.listKubernetesProvidersAndPermissionsReturns
	fake.recordInvocation("ListKubernetesProvidersAndPermissions", []interface{}{})
	fake.listKubernetesProvidersAndPermissionsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) ListKubernetesProvidersAndPermissionsCallCount() int {
	fake.listKubernetesProvidersAndPermissionsMutex.RLock()
	defer fake.listKubernetesProvidersAndPermissionsMutex.RUnlock()
	return len(fake.listKubernetesProvidersAndPermissionsArgsForCall)
}

func (fake *FakeClient) ListKubernetesProvidersAndPermissionsCalls(stub func() ([]kubernetes.Provider, error)) {
	fake.listKubernetesProvidersAndPermissionsMutex.Lock()
	defer fake.listKubernetesProvidersAndPermissionsMutex.Unlock()
	fake.ListKubernetesProvidersAndPermissionsStub = stub
}

func (fake *FakeClient) ListKubernetesProvidersAndPermissionsReturns(result1 []kubernetes.Provider, result2 error) {
	fake.listKubernetesProvidersAndPermissionsMutex.Lock()
	defer fake.listKubernetesProvidersAndPermissionsMutex.Unlock()
	fake.ListKubernetesProvidersAndPermissionsStub = nil
	fake.listKubernetesProvidersAndPermissionsReturns = struct {
		result1 []kubernetes.Provider
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListKubernetesProvidersAndPermissionsReturnsOnCall(i int, result1 []kubernetes.Provider, result2 error) {
	fake.listKubernetesProvidersAndPermissionsMutex.Lock()
	defer fake.listKubernetesProvidersAndPermissionsMutex.Unlock()
	fake.ListKubernetesProvidersAndPermissionsStub = nil
	if fake.listKubernetesProvidersAndPermissionsReturnsOnCall == nil {
		fake.listKubernetesProvidersAndPermissionsReturnsOnCall = make(map[int]struct {
			result1 []kubernetes.Provider
			result2 error
		})
	}
	fake.listKubernetesProvidersAndPermissionsReturnsOnCall[i] = struct {
		result1 []kubernetes.Provider
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListKubernetesResourcesByFields(arg1 ...string) ([]kubernetes.Resource, error) {
	fake.listKubernetesResourcesByFieldsMutex.Lock()
	ret, specificReturn := fake.listKubernetesResourcesByFieldsReturnsOnCall[len(fake.listKubernetesResourcesByFieldsArgsForCall)]
	fake.listKubernetesResourcesByFieldsArgsForCall = append(fake.listKubernetesResourcesByFieldsArgsForCall, struct {
		arg1 []string
	}{arg1})
	stub := fake.ListKubernetesResourcesByFieldsStub
	fakeReturns := fake.listKubernetesResourcesByFieldsReturns
	fake.recordInvocation("ListKubernetesResourcesByFields", []interface{}{arg1})
	fake.listKubernetesResourcesByFieldsMutex.Unlock()
	if stub != nil {
		return stub(arg1...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) ListKubernetesResourcesByFieldsCallCount() int {
	fake.listKubernetesResourcesByFieldsMutex.RLock()
	defer fake.listKubernetesResourcesByFieldsMutex.RUnlock()
	return len(fake.listKubernetesResourcesByFieldsArgsForCall)
}

func (fake *FakeClient) ListKubernetesResourcesByFieldsCalls(stub func(...string) ([]kubernetes.Resource, error)) {
	fake.listKubernetesResourcesByFieldsMutex.Lock()
	defer fake.listKubernetesResourcesByFieldsMutex.Unlock()
	fake.ListKubernetesResourcesByFieldsStub = stub
}

func (fake *FakeClient) ListKubernetesResourcesByFieldsArgsForCall(i int) []string {
	fake.listKubernetesResourcesByFieldsMutex.RLock()
	defer fake.listKubernetesResourcesByFieldsMutex.RUnlock()
	argsForCall := fake.listKubernetesResourcesByFieldsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) ListKubernetesResourcesByFieldsReturns(result1 []kubernetes.Resource, result2 error) {
	fake.listKubernetesResourcesByFieldsMutex.Lock()
	defer fake.listKubernetesResourcesByFieldsMutex.Unlock()
	fake.ListKubernetesResourcesByFieldsStub = nil
	fake.listKubernetesResourcesByFieldsReturns = struct {
		result1 []kubernetes.Resource
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListKubernetesResourcesByFieldsReturnsOnCall(i int, result1 []kubernetes.Resource, result2 error) {
	fake.listKubernetesResourcesByFieldsMutex.Lock()
	defer fake.listKubernetesResourcesByFieldsMutex.Unlock()
	fake.ListKubernetesResourcesByFieldsStub = nil
	if fake.listKubernetesResourcesByFieldsReturnsOnCall == nil {
		fake.listKubernetesResourcesByFieldsReturnsOnCall = make(map[int]struct {
			result1 []kubernetes.Resource
			result2 error
		})
	}
	fake.listKubernetesResourcesByFieldsReturnsOnCall[i] = struct {
		result1 []kubernetes.Resource
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListKubernetesResourcesByTaskID(arg1 string) ([]kubernetes.Resource, error) {
	fake.listKubernetesResourcesByTaskIDMutex.Lock()
	ret, specificReturn := fake.listKubernetesResourcesByTaskIDReturnsOnCall[len(fake.listKubernetesResourcesByTaskIDArgsForCall)]
	fake.listKubernetesResourcesByTaskIDArgsForCall = append(fake.listKubernetesResourcesByTaskIDArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ListKubernetesResourcesByTaskIDStub
	fakeReturns := fake.listKubernetesResourcesByTaskIDReturns
	fake.recordInvocation("ListKubernetesResourcesByTaskID", []interface{}{arg1})
	fake.listKubernetesResourcesByTaskIDMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) ListKubernetesResourcesByTaskIDCallCount() int {
	fake.listKubernetesResourcesByTaskIDMutex.RLock()
	defer fake.listKubernetesResourcesByTaskIDMutex.RUnlock()
	return len(fake.listKubernetesResourcesByTaskIDArgsForCall)
}

func (fake *FakeClient) ListKubernetesResourcesByTaskIDCalls(stub func(string) ([]kubernetes.Resource, error)) {
	fake.listKubernetesResourcesByTaskIDMutex.Lock()
	defer fake.listKubernetesResourcesByTaskIDMutex.Unlock()
	fake.ListKubernetesResourcesByTaskIDStub = stub
}

func (fake *FakeClient) ListKubernetesResourcesByTaskIDArgsForCall(i int) string {
	fake.listKubernetesResourcesByTaskIDMutex.RLock()
	defer fake.listKubernetesResourcesByTaskIDMutex.RUnlock()
	argsForCall := fake.listKubernetesResourcesByTaskIDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) ListKubernetesResourcesByTaskIDReturns(result1 []kubernetes.Resource, result2 error) {
	fake.listKubernetesResourcesByTaskIDMutex.Lock()
	defer fake.listKubernetesResourcesByTaskIDMutex.Unlock()
	fake.ListKubernetesResourcesByTaskIDStub = nil
	fake.listKubernetesResourcesByTaskIDReturns = struct {
		result1 []kubernetes.Resource
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListKubernetesResourcesByTaskIDReturnsOnCall(i int, result1 []kubernetes.Resource, result2 error) {
	fake.listKubernetesResourcesByTaskIDMutex.Lock()
	defer fake.listKubernetesResourcesByTaskIDMutex.Unlock()
	fake.ListKubernetesResourcesByTaskIDStub = nil
	if fake.listKubernetesResourcesByTaskIDReturnsOnCall == nil {
		fake.listKubernetesResourcesByTaskIDReturnsOnCall = make(map[int]struct {
			result1 []kubernetes.Resource
			result2 error
		})
	}
	fake.listKubernetesResourcesByTaskIDReturnsOnCall[i] = struct {
		result1 []kubernetes.Resource
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListReadGroupsByAccountName(arg1 string) ([]string, error) {
	fake.listReadGroupsByAccountNameMutex.Lock()
	ret, specificReturn := fake.listReadGroupsByAccountNameReturnsOnCall[len(fake.listReadGroupsByAccountNameArgsForCall)]
	fake.listReadGroupsByAccountNameArgsForCall = append(fake.listReadGroupsByAccountNameArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ListReadGroupsByAccountNameStub
	fakeReturns := fake.listReadGroupsByAccountNameReturns
	fake.recordInvocation("ListReadGroupsByAccountName", []interface{}{arg1})
	fake.listReadGroupsByAccountNameMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) ListReadGroupsByAccountNameCallCount() int {
	fake.listReadGroupsByAccountNameMutex.RLock()
	defer fake.listReadGroupsByAccountNameMutex.RUnlock()
	return len(fake.listReadGroupsByAccountNameArgsForCall)
}

func (fake *FakeClient) ListReadGroupsByAccountNameCalls(stub func(string) ([]string, error)) {
	fake.listReadGroupsByAccountNameMutex.Lock()
	defer fake.listReadGroupsByAccountNameMutex.Unlock()
	fake.ListReadGroupsByAccountNameStub = stub
}

func (fake *FakeClient) ListReadGroupsByAccountNameArgsForCall(i int) string {
	fake.listReadGroupsByAccountNameMutex.RLock()
	defer fake.listReadGroupsByAccountNameMutex.RUnlock()
	argsForCall := fake.listReadGroupsByAccountNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) ListReadGroupsByAccountNameReturns(result1 []string, result2 error) {
	fake.listReadGroupsByAccountNameMutex.Lock()
	defer fake.listReadGroupsByAccountNameMutex.Unlock()
	fake.ListReadGroupsByAccountNameStub = nil
	fake.listReadGroupsByAccountNameReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListReadGroupsByAccountNameReturnsOnCall(i int, result1 []string, result2 error) {
	fake.listReadGroupsByAccountNameMutex.Lock()
	defer fake.listReadGroupsByAccountNameMutex.Unlock()
	fake.ListReadGroupsByAccountNameStub = nil
	if fake.listReadGroupsByAccountNameReturnsOnCall == nil {
		fake.listReadGroupsByAccountNameReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.listReadGroupsByAccountNameReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListWriteGroupsByAccountName(arg1 string) ([]string, error) {
	fake.listWriteGroupsByAccountNameMutex.Lock()
	ret, specificReturn := fake.listWriteGroupsByAccountNameReturnsOnCall[len(fake.listWriteGroupsByAccountNameArgsForCall)]
	fake.listWriteGroupsByAccountNameArgsForCall = append(fake.listWriteGroupsByAccountNameArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ListWriteGroupsByAccountNameStub
	fakeReturns := fake.listWriteGroupsByAccountNameReturns
	fake.recordInvocation("ListWriteGroupsByAccountName", []interface{}{arg1})
	fake.listWriteGroupsByAccountNameMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) ListWriteGroupsByAccountNameCallCount() int {
	fake.listWriteGroupsByAccountNameMutex.RLock()
	defer fake.listWriteGroupsByAccountNameMutex.RUnlock()
	return len(fake.listWriteGroupsByAccountNameArgsForCall)
}

func (fake *FakeClient) ListWriteGroupsByAccountNameCalls(stub func(string) ([]string, error)) {
	fake.listWriteGroupsByAccountNameMutex.Lock()
	defer fake.listWriteGroupsByAccountNameMutex.Unlock()
	fake.ListWriteGroupsByAccountNameStub = stub
}

func (fake *FakeClient) ListWriteGroupsByAccountNameArgsForCall(i int) string {
	fake.listWriteGroupsByAccountNameMutex.RLock()
	defer fake.listWriteGroupsByAccountNameMutex.RUnlock()
	argsForCall := fake.listWriteGroupsByAccountNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) ListWriteGroupsByAccountNameReturns(result1 []string, result2 error) {
	fake.listWriteGroupsByAccountNameMutex.Lock()
	defer fake.listWriteGroupsByAccountNameMutex.Unlock()
	fake.ListWriteGroupsByAccountNameStub = nil
	fake.listWriteGroupsByAccountNameReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListWriteGroupsByAccountNameReturnsOnCall(i int, result1 []string, result2 error) {
	fake.listWriteGroupsByAccountNameMutex.Lock()
	defer fake.listWriteGroupsByAccountNameMutex.Unlock()
	fake.ListWriteGroupsByAccountNameStub = nil
	if fake.listWriteGroupsByAccountNameReturnsOnCall == nil {
		fake.listWriteGroupsByAccountNameReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.listWriteGroupsByAccountNameReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) WithConfig(arg1 *gorm.Config) {
	fake.withConfigMutex.Lock()
	fake.withConfigArgsForCall = append(fake.withConfigArgsForCall, struct {
		arg1 *gorm.Config
	}{arg1})
	stub := fake.WithConfigStub
	fake.recordInvocation("WithConfig", []interface{}{arg1})
	fake.withConfigMutex.Unlock()
	if stub != nil {
		fake.WithConfigStub(arg1)
	}
}

func (fake *FakeClient) WithConfigCallCount() int {
	fake.withConfigMutex.RLock()
	defer fake.withConfigMutex.RUnlock()
	return len(fake.withConfigArgsForCall)
}

func (fake *FakeClient) WithConfigCalls(stub func(*gorm.Config)) {
	fake.withConfigMutex.Lock()
	defer fake.withConfigMutex.Unlock()
	fake.WithConfigStub = stub
}

func (fake *FakeClient) WithConfigArgsForCall(i int) *gorm.Config {
	fake.withConfigMutex.RLock()
	defer fake.withConfigMutex.RUnlock()
	argsForCall := fake.withConfigArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.connectMutex.RLock()
	defer fake.connectMutex.RUnlock()
	fake.createKubernetesProviderMutex.RLock()
	defer fake.createKubernetesProviderMutex.RUnlock()
	fake.createKubernetesResourceMutex.RLock()
	defer fake.createKubernetesResourceMutex.RUnlock()
	fake.deleteKubernetesProviderMutex.RLock()
	defer fake.deleteKubernetesProviderMutex.RUnlock()
	fake.deleteKubernetesResourcesByAccountNameMutex.RLock()
	defer fake.deleteKubernetesResourcesByAccountNameMutex.RUnlock()
	fake.getKubernetesProviderMutex.RLock()
	defer fake.getKubernetesProviderMutex.RUnlock()
	fake.getKubernetesProviderAndPermissionsMutex.RLock()
	defer fake.getKubernetesProviderAndPermissionsMutex.RUnlock()
	fake.listKubernetesAccountsBySpinnakerAppMutex.RLock()
	defer fake.listKubernetesAccountsBySpinnakerAppMutex.RUnlock()
	fake.listKubernetesClustersByApplicationMutex.RLock()
	defer fake.listKubernetesClustersByApplicationMutex.RUnlock()
	fake.listKubernetesClustersByFieldsMutex.RLock()
	defer fake.listKubernetesClustersByFieldsMutex.RUnlock()
	fake.listKubernetesProvidersMutex.RLock()
	defer fake.listKubernetesProvidersMutex.RUnlock()
	fake.listKubernetesProvidersAndPermissionsMutex.RLock()
	defer fake.listKubernetesProvidersAndPermissionsMutex.RUnlock()
	fake.listKubernetesResourcesByFieldsMutex.RLock()
	defer fake.listKubernetesResourcesByFieldsMutex.RUnlock()
	fake.listKubernetesResourcesByTaskIDMutex.RLock()
	defer fake.listKubernetesResourcesByTaskIDMutex.RUnlock()
	fake.listReadGroupsByAccountNameMutex.RLock()
	defer fake.listReadGroupsByAccountNameMutex.RUnlock()
	fake.listWriteGroupsByAccountNameMutex.RLock()
	defer fake.listWriteGroupsByAccountNameMutex.RUnlock()
	fake.withConfigMutex.RLock()
	defer fake.withConfigMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sql.Client = new(FakeClient)
